openapi: 3.0.0
info:
  title: API Marketplace Chatbot
  version: 0.1.0
paths:
  /:
    summary: Say Hello
    get:
      summary: sayHello
      operationId: SayHello
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema: {}
